# Generated by Django 5.0.9 on 2024-11-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medico_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleboleta',
            name='bodega',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='detalleboleta',
            name='boleta',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='medico',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Bodega',
        ),
        migrations.DeleteModel(
            name='Boleta',
        ),
        migrations.DeleteModel(
            name='DetalleBoleta',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
