# Generated by Django 5.0.9 on 2024-11-19 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_detalleboleta_bodega_remove_boleta_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='numero_documento',
            field=models.CharField(default='123456789', max_length=20, verbose_name='Número de documento'),
        ),
        migrations.AddField(
            model_name='cita',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('PASAPORTE', 'Pasaporte'), ('CEDULA', 'Cédula de Identidad')], default='DNI', max_length=20, verbose_name='Tipo de documento de identidad'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='subscrito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Doctor', 'Doctor'), ('Administrador', 'Administrador'), ('Superusuario', 'Superusuario')], max_length=50, verbose_name='Tipo de usuario'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.especialidad'),
        ),
    ]
