# Generated by Django 5.0.9 on 2024-11-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_especialidad_cita_numero_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Medico', 'Medico'), ('Administrador', 'Administrador'), ('Superusuario', 'Superusuario')], max_length=50, verbose_name='Tipo de usuario'),
        ),
    ]
